### ISSUE TITLE
Conflict with item zoom mod

### ISSUE THREAD

**Issue by slainless** [Darkhax-Minecraft/Coloured-Tooltips#5]
It seems to broke Item Zoom mod.
IZ cant display the zoomed item properly when opening inventory.

to reproduce:
- 1.12.2
- mod used : JEI, CT & IZ
- forge 2847

**Comment by slainless** [comment]
my bad. looks like its caused by another mod

**Comment by SeriousCreeper** [comment]
@xtrial remember which one? Having the same issue (as well as Thaumcraft aspects not showing on tooltips)

**Comment by slainless** [comment]
another mod with almost same name 'Colored Tooltips'. switched that with darkhax version and problem solved.
i hope thats solve yours

**Comment by SeriousCreeper** [comment]
Oh woops, i think i was using that one too. Thanks, will switch.
