### ISSUE TITLE
Obligatory 1.16.4 Please Request

### ISSUE THREAD

**Issue by Darkosto** [Darkhax-Minecraft/Coloured-Tooltips#6]
Any chance you're able to update this to 1.16.4?

Thanks!! <3

**Comment by Darkhax** [comment]
Hey, 

I am hoping to update all of my 1.16.3 mods to 1.16.4 in the next few days.

**Comment by Darkhax** [comment]
There we go, now up for [1.16.3](https://www.curseforge.com/minecraft/mc-mods/coloured-tooltips/files/3111063) and [1.16.4](https://www.curseforge.com/minecraft/mc-mods/coloured-tooltips/files/3111059).
